In [1]:
import pandas as pd
import os, sys
from sklearn.gaussian_process import GaussianProcessRegressor
import shapefile
from functools import partial
import pyproj
from shapely.geometry import shape, Point, mapping
from shapely.ops import transform
processeddir = "../data/processed/"
rawdir = "../data/raw/"
df = pd.read_csv(os.path.join(processeddir,"nyctaxiclean.csv"), dtype={"store_and_fwd_flag": "object"})

In [2]:
df["pickup_float"] = pd.to_datetime(df["pickup_datetime"]).apply(lambda x: x.timestamp())
df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])
df["dropoff_datetime"] = pd.to_datetime(df["dropoff_datetime"])
df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])
df["dropoff_datetime"] = pd.to_datetime(df["dropoff_datetime"])

In [3]:
#get centroids from shapesfile from NYC taxi

def get_centroids(filename=rawdir+"taxi_zones/taxi_zones"):
    sf = shapefile.Reader(filename)

    project = partial(
        pyproj.transform,
        pyproj.Proj(init='epsg:2263', preserve_units=True), # NAD_1983_StatePlane_New_York_Long_Island_FIPS_3104_Feet
        pyproj.Proj(init='epsg:4326')) # wgs84 (lat/lng) 
 
    centroids = list(map(lambda x: transform(project, shape(x.__geo_interface__)).centroid, sf.shapes()))
    
    df = pd.DataFrame(sf.records())
    df = df.rename(columns={3:"name"})
    df["centroid_x"] = list(map(lambda x: x.x, centroids))
    df["centroid_y"] = list(map(lambda x: x.y, centroids))
    return df

centroid_df = get_centroids()

In [4]:
df["pickup_hour"] = df["pickup_datetime"].apply(lambda x: x.hour)
df["pickup_dayofweek"] = df["pickup_datetime"].apply(lambda x: x.weekday())
df["pickup_dayofmonth"] = df["pickup_datetime"].apply(lambda x: x.day)


In [5]:
centroid_dataset = df.merge(centroid_df, left_on="pickup_neighbourhood", right_on="name")
centroid_dataset

Unnamed: 0                         medallion  \
0                  0  91F6EB84975BBC867E32CB113C7C2CD5   
1                  9  13A57EE874E2560DF1F9D6C639BB7DAB   
2                 32  D83519B044B750F146A3A349197C80AA   
3                 72  8FDE065D961FFE6CB6B4CA1F47525C6D   
4                106  34EA29ABFCE6B78138FEA90D330101B1   
5                117  30DB18A7927FB0496BF91BEA23D961E9   
6                151  2D1FD2323BE2C8C086FFE5661888892D   
7                238  385B40B09DF15C8D150AF46E1B4A3AB4   
8                290  FD9900398CC8CBEF7D3E7890FA854FA2   
9                326  78FD0655D0CBD598C17BFA40654850E2   
10               382  4B20C5B8EBF5D6A4A14C928DF5AD99E9   
11               385  311320DD8732526CA6525BD9CAD9F5A7   
12               403  0A415B814A6479EE706972D2FD6DA08A   
13               485  E6401D4037661AD0077ACB6077BBB2AE   
14               492  4162621AC1829E9675EED8B3E2B4C464   
15               497  02CEBCE78642047165DD6E729BF7E3AC   
16               696  DF85538DFDC1347EB6A42B1362077A2D   
17               753  6816A8A4203980A7D9B19DA5FA9E845B   
18               773  CA93F8576A51663C409C3DC2CA836DE8   
19               780  3E29713986A6762D985C4FC53B177F61   
20               846  E2D92DC49D2E3A841FFCE27ADA3921F0   
21               854  FE444AF957F4ACED1BB0275389C071CC   
22               920  123762F2C365CFF2A030A8F47A435ED9   
23               984  A8EE7FD7022C9E58BE8F096D347EE0B8   
24              1018  5F5C74564DB2AD39E049BC65354EEFB5   
25              1050  C61EBE0BFDD0A348B083267DE989FEF5   
26              1094  253508A1EBFC63BF5DFB4361EAE83703   
27              1104  09459F826A44348760E74FCD3BFBDB72   
28              1130  2D76170B2CC1D22099C499F76910B4E1   
29              1169  1FFE6E69C0B4762235E9885B7FB0749C   
...              ...                               ...   
14817214    12576759  D924885BA122B60895801D9C11191182   
14817215    12724162  D86D7A22BADAEE364C83543982CF291A   
14817216    12724162  D86D7A22BADAEE364C83543982CF291A   
14817217    12724162  D86D7A22BADAEE364C83543982CF291A   
14817218    13345595  B6EA16667573BC4128A52741FEC5E703   
14817219    13345595  B6EA16667573BC4128A52741FEC5E703   
14817220    13345595  B6EA16667573BC4128A52741FEC5E703   
14817221     4938313  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817222     8449505  0ADC532C1F6519BC7002D0AE338FDA52   
14817223    11047031  9F3A7F7CAC9626F5A8A1D24C5704AD93   
14817224     4970555  EF9C8C5CBDC67FFF33367714161530ED   
14817225     7967231  98C1BBAD5CAA169896BBCA5D98A5358F   
14817226     9008568  C8C0883037778AB88FA31A0A673DC91F   
14817227     9081134  8D862648A42EEF08D29AD669EFB562E7   
14817228    13239130  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817229     5741464  7D12FC75A27AE3ECD0010D0A3987AC96   
14817230    10922585  B749FB0AD2D9FDF9E24F637EC0C40477   
14817231    11062708  D647D82A8DB7E741EFE115A29CA74322   
14817232    13036865  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817233    13697602  1F1421F19C402922AED22ECDCD4539B2   
14817234    13752895  D819478C009EEB1C921B55DA39FED54C   
14817235     8945060  8CE757F6FB166778D9B279F83C9904E0   
14817236    11233553  5D7054D121F7AFEF5D67FD93AB1DF05E   
14817237    12242870  E523F84E85708BCEB9FEB6F7825C0E08   
14817238    12617866  DD92AF6B9CDDFD851B39233F61907FFA   
14817239    13078302  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817240    13017007  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817241    13054985  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817242    13336875  BC4CB3D01850D3EC81B9D7A257D2CB18   
14817243    13962208  97D167499FF0A1F60E55656B291801D7   

                              hack_license vendor_id_x  rate_code  \
0         AD8751110E6292079EB10EB9481FE1A6         CMT          1   
1         5FE3733438871FE98C05D259E8693750         CMT          1   
2         321DDAF4C11879A55D71E254A3CCFFA5         CMT          1   
3         5A81C4DD7805B2F8686398C7D42FC2C7         CMT          1   
4         9C47390E9A6BB2C8C6CBCEB388612AE4         CMT          1   

In [114]:
#predict a fare given startpoint and destination

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
# 4 POC neighbourhoods
chosen_neighbourhoods = ["Upper East Side South", "Midtown Center", "Flatiron", "JFK Airport"]

# as this dataset is not aggregated we can use random 4-fold CV
kf = KFold(n_splits=4, shuffle=True)

fare_models = []
preds = []
rmse = []
neigh_df = centroid_dataset[centroid_dataset["pickup_neighbourhood"].isin(chosen_neighbourhoods)][["pickup_hour", "pickup_dayofweek", "dropoff_longitude", "dropoff_latitude", "fare_amount", "tip_amount"]]
for train_index, test_index in kf.split(neigh_df):
    fare_model = RandomForestRegressor()
    fare_models.append(fare_model)
    train_df = neigh_df.iloc[train_index]
    test_df = neigh_df.iloc[test_index]
    x_keys = ["pickup_hour", "pickup_dayofweek", "dropoff_longitude", "dropoff_latitude"]
    y_keys = ["fare_amount", "tip_amount"]
    fare_model.fit(train_df[x_keys], train_df[y_keys])

    preds.append(fare_model.predict(test_df[x_keys]))
    rmse.append((np.sqrt(mean_squared_error(test_df[y_keys[0]],[x[0] for x in preds[-1]])), 
            np.sqrt(mean_squared_error(test_df[y_keys[1]],[x[1] for x in preds[-1]]))))

print(rmse)

[(12.747741367747816, 2.8565813319770026), (12.748133130203438, 2.8748881960663355), (12.734691955499766, 2.8709108283870015), (12.778356007727016, 2.851119346700868)]


In [117]:
np.std([x[1] for x in rmse])

0.009819589554984033

In [120]:
fare_models[-1].feature_importances_

array([0.08336131, 0.06578142, 0.39830618, 0.4525511 ])

In [132]:
#predict a fare given time of day and pickup neighbourhood

chosen_neighbourhoods = ["Upper East Side South", "Midtown Center", "Flatiron", "JFK Airport"]

# as this dataset is not aggregated we can use random 4-fold CV
kf = KFold(n_splits=4, shuffle=True)

fare_models = []
preds = []
rmse = []
neigh_df = centroid_dataset[centroid_dataset["pickup_neighbourhood"].isin(chosen_neighbourhoods)][["pickup_hour", "pickup_dayofweek", "pickup_neighbourhood", "fare_amount", "tip_amount"]]

#OHE the pickup_neighbourhood
for i in range(len(chosen_neighbourhoods)):
    neigh_df[i] = (neigh_df["pickup_neighbourhood"] == chosen_neighbourhoods[i]).astype(int)
    
neigh_df = neigh_df.drop("pickup_neighbourhood", axis=1)

In [134]:
for train_index, test_index in kf.split(neigh_df):
    fare_model = RandomForestRegressor()
    fare_models.append(fare_model)
    train_df = neigh_df.iloc[train_index]
    test_df = neigh_df.iloc[test_index]
    x_keys = ["pickup_hour", "pickup_dayofweek"] + list(range(len(chosen_neighbourhoods)))
    y_keys = ["fare_amount", "tip_amount"]
    fare_model.fit(train_df[x_keys], train_df[y_keys])

    preds.append(fare_model.predict(test_df[x_keys]))
    rmse.append((np.sqrt(mean_squared_error(test_df[y_keys[0]],[x[0] for x in preds[-1]])), 
            np.sqrt(mean_squared_error(test_df[y_keys[1]],[x[1] for x in preds[-1]]))))

print(rmse)

[(8.940778962999726, 2.5948808784499064), (8.792814718379235, 2.581849826891663), (8.760484044953822, 2.568522295371402), (8.784875548938043, 2.579961548953915)]


In [138]:
np.std([x[1] for x in rmse])

0.009351519969197294

what follows is the unsuccessful attempt at training KDE on this data; preserved for reference

In [18]:
from statsmodels.nonparametric.kernel_density import KDEMultivariate
from sklearn.model_selection import KFold
# 4 POC neighbourhoods
chosen_neighbourhoods = ["Upper East Side South", "Midtown Center", "Flatiron", "JFK Airport"]

# as this dataset is not aggregated we can use random 4-fold CV
kf = KFold(n_splits=4, shuffle=True)

kde_models = []
likelihood = []
for neigh in chosen_neighbourhoods:
    neigh_df = centroid_dataset[centroid_dataset["pickup_neighbourhood"] == neigh][["pickup_hour", "pickup_dayofweek", "dropoff_longitude", "dropoff_latitude", "fare_amount", "tip_amount"]]
    for train_index, test_index in kf.split(neigh_df):
        train_df = neigh_df.iloc[train_index]
        test_df = neigh_df.iloc[test_index]
        kde_models.append(KDEMultivariate(train_df, var_type='oocccc'))
        likelihood.append(kde_models[-1].pdf(test_df))

In [20]:
import numpy as np

kde_models = []
centroid_dataset["fare_tip"] = centroid_dataset["fare_amount"] + centroid_dataset["tip_amount"]
for neigh in chosen_neighbourhoods:
    neigh_df = centroid_dataset[centroid_dataset["pickup_neighbourhood"] == neigh][["pickup_hour", "pickup_dayofweek", "dropoff_longitude", "dropoff_latitude", "fare_tip"]]
    kde_models.append(KDEMultivariate(neigh_df, var_type='ooccc'))



In [55]:
# also estimate probability of given event
# P(y|x) = P(y,x)/P(x)
x_models = []
for neigh in chosen_neighbourhoods:
    neigh_df = centroid_dataset[centroid_dataset["pickup_neighbourhood"] == neigh][["pickup_hour", "pickup_dayofweek", "dropoff_longitude", "dropoff_latitude"]]
    x_models.append(KDEMultivariate(neigh_df, var_type='oocc'))

In [24]:
grouped_df = df.groupby("pickup_neighbourhood")
sig_neigh = grouped_df.count().sort_values("medallion", ascending=False).index[:50]

In [28]:
sig_centroids = centroid_df[centroid_df["name"].isin(sig_neigh)]

In [65]:
len(y_x_data[0])

1

In [100]:
y_x = []
x = []
fares = np.linspace(1,100,25)
probs = []
x_data = [[0, 0, y["centroid_x"], y["centroid_y"]] for i, y in sig_centroids.iterrows()]   
y_x_data = [[y + [j]] for y in x_data for j in fares]

for i, neigh in enumerate(chosen_neighbourhoods):
    x.append(x_models[i].cdf(x_data[i]))
    y_x.append(kde_models[i].cdf(y_x_data)) # cdf probability that it's less than this fare
    probs.append(np.exp(y_x[-1] - x[-1])) # baye's theorem... np.exp because we have log likelihood
len(probs)

4

In [102]:
probs[0]

array([1.0003423 , 0.98137904, 0.93529751, ..., 0.85124727, 0.85124068,
       0.85123168])

In [81]:
len(fares)

25

In [95]:
centroid_df[centroid_df["name"].isin(chosen_neighbourhoods)]


0         1         2                   name    4          5  \
89    90  0.030759  0.000055               Flatiron   90  Manhattan   
131  132  0.245479  0.002038            JFK Airport  132     Queens   
160  161  0.035804  0.000072         Midtown Center  161  Manhattan   
236  237  0.042213  0.000096  Upper East Side South  237  Manhattan   

     centroid_x  centroid_y  
89   -73.996971   40.742279  
131  -73.786533   40.646985  
160  -73.977698   40.758028  
236  -73.965635   40.768615

In [50]:
fares

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])